### ISSUE TITLE
[Bug] Get an error when I use mail

### ISSUE THREAD

**Issue by Gktwo** [Grasscutters/Grasscutter#1307]
java.lang.NullPointerException: Cannot read field "itemId" because "item" is null
        at emu.grasscutter.server.packet.send.PacketGetAllMailRsp.<init>(PacketGetAllMailRsp.java:48)
        at emu.grasscutter.server.packet.recv.HandlerGetAllMailReq.handle(HandlerGetAllMailReq.java:19)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:224)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Birdulon** [comment]
Please follow the issue template and provide more information to help us understand what you are doing to encounter this.
