### ISSUE TITLE
[Bug]  3.3编译后执行报错

### ISSUE THREAD

**Issue by mcoi-dev** [Grasscutters/Grasscutter#2000]
**Describe the bug**

最新版本`dev`分支编译后分别使用[这个](https://git.crepe.moe/grasscutters/Grasscutter_Resources/-/tree/ww-3.3)还有[这个](https://git.crepe.moe/grasscutters/Grasscutter_Resources/-/tree/3.3)`Resources`运行，都会有类似以下的报错：

```text
[17:46:55] [[34mINFO[0;39m] Starting Grasscutter...
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [AvatarTalentExcelConfigData.json]
java.lang.NullPointerException: Cannot read the array length because the return value of "emu.grasscutter.data.def.AvatarTalentData.getAddProps()" is null
        at emu.grasscutter.data.def.AvatarTalentData.onLoad(AvatarTalentData.java:60)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:123)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
[17:46:56] [[34mINFO[0;39m] Loaded 1 AvatarSkillDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 FetterDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 AvatarSkillDepotDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 MonsterDescribeDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 AvatarCostumeDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 NpcDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 ReliquaryMainPropDatas.
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [MonsterCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:119)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 10 common frames omitted
[17:46:56] [[34mINFO[0;39m] Loaded 1 SceneDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 AvatarLevelDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 ItemDatas.
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [AvatarPromoteExcelConfigData.json]
java.lang.NullPointerException: Cannot read the array length because the return value of "emu.grasscutter.data.def.AvatarPromoteData.getAddProps()" is null
        at emu.grasscutter.data.def.AvatarPromoteData.onLoad(AvatarPromoteData.java:56)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:123)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
[17:46:56] [[34mINFO[0;39m] Loaded 1 ReliquaryAffixDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 WeaponLevelDatas.
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [WeaponPromoteExcelConfigData.json]
java.lang.NullPointerException: Cannot read the array length because the return value of "emu.grasscutter.data.def.WeaponPromoteData.getAddProps()" is null
        at emu.grasscutter.data.def.WeaponPromoteData.onLoad(WeaponPromoteData.java:56)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:123)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
[17:46:56] [[34mINFO[0;39m] Loaded 1 AvatarFlycloakDatas.
[17:46:56] [[34mINFO[0;39m] Loaded 1 GadgetDatas.
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [AvatarCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:119)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 10 common frames omitted
[17:46:56] [[34mINFO[0;39m] Loaded 1 ReliquarySetDatas.
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [WeaponCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:119)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 10 common frames omitted
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [EquipAffixExcelConfigData.json]
java.lang.NullPointerException: Cannot read the array length because the return value of "emu.grasscutter.data.def.EquipAffixData.getAddProps()" is null
        at emu.grasscutter.data.def.EquipAffixData.onLoad(EquipAffixData.java:50)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:123)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
[17:46:56] [[34mINFO[0;39m] Loaded 1 PlayerLevelDatas.
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [ReliquaryLevelExcelConfigData.json]
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.AddProps" is null
        at emu.grasscutter.data.def.ReliquaryLevelData.onLoad(ReliquaryLevelData.java:50)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:123)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [ProudSkillExcelConfigData.json]
java.lang.NullPointerException: Cannot invoke "String.length()" because the return value of "emu.grasscutter.data.def.ProudSkillData.getOpenConfig()" is null
        at emu.grasscutter.data.def.ProudSkillData.onLoad(ProudSkillData.java:88)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:123)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [MonsterExcelConfigData.json]
java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
        at emu.grasscutter.data.def.MonsterData.onLoad(MonsterData.java:173)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:123)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
[17:46:56] [[1;31mERROR[0;39m] Error loading resource file: [AvatarExcelConfigData.json]
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "this.IconName" is null
        at emu.grasscutter.data.def.AvatarData.onLoad(AvatarData.java:241)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:123)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:111)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:101)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:48)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
[17:46:56] [[1;31mERROR[0;39m] Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.
[17:46:56] [[1;31mERROR[0;39m] Error loading abilities
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.def.AvatarSkillDepotData.setAbilities(emu.grasscutter.data.custom.AbilityEmbryoEntry)" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:54)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)
[17:46:56] [[34mINFO[0;39m] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[17:46:56] [[34mINFO[0;39m] Opened connection [connectionId{localValue:1, serverValue:11}] to localhost:27017
[17:46:56] [[34mINFO[0;39m] Opened connection [connectionId{localValue:2, serverValue:10}] to localhost:27017
[17:46:56] [[34mINFO[0;39m] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=23230100}
[17:46:56] [[34mINFO[0;39m] Opened connection [connectionId{localValue:3, serverValue:12}] to localhost:27017
[17:46:57] [[31mWARN[0;39m] [Dispatch] No SSL cert found! Falling back to HTTP server.
Exception in thread "main" java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
        at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:142)
        at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
        at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
        at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(HttpServer.java:150)
        at emu.grasscutter.server.dispatch.DispatchServer.start(DispatchServer.java:182)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:78)
```

之前3.2的时候都没有的

**Comment by mcoi-dev** [comment]
似乎是`resorses`的错误，有些`json`读取出错

**Comment by mcoi-dev** [comment]
现在解决了，是镜像站没同步
